export const ROSTER = [
  {
    id: "lilo",
    name: "Lilo",
    color: "#e23b3b",
    speed: 4.4,
    jumpPower: 13.2,
    maxJumps: 1,
    health: 110,
    w: 28,
    h: 42,
    abilities: ["ukulele", "hula", "ohana"],
    evoNames: ["Lilo", "Guardián Ohana", "Alma de Kauai"],
  },
  {
    id: "stitch",
    name: "Stitch",
    color: "#3b6cff",
    speed: 5.4,
    jumpPower: 12.4,
    maxJumps: 2,
    health: 130,
    w: 36,
    h: 32,
    abilities: ["dash", "claws", "exp626"],
    evoNames: ["Stitch", "Berserk 626", "Experiment MAX"],
  },
  {
    id: "pikachu",
    name: "Pikachu",
    color: "#f5d000",
    speed: 6.2,
    jumpPower: 14.2,
    maxJumps: 2,
    health: 80,
    w: 30,
    h: 28,
    abilities: ["shock", "quick", "thunder"],
    evoNames: ["Pikachu", "Raichu", "Tormenta"],
  },
  {
    id: "dragon",
    name: "Dragón",
    color: "#ff6a2a",
    speed: 3.8,
    jumpPower: 11.5,
    maxJumps: 1,
    glide: true,
    health: 180,
    w: 52,
    h: 44,
    abilities: ["breath", "wing", "rage"],
    evoNames: ["Cría", "Dragón de Fuego", "Volcánico"],
  },
  {
    id: "cat",
    name: "Kawaii Cat",
    color: "#ff8ad4",
    speed: 5.8,
    jumpPower: 12.8,
    maxJumps: 3,
    health: 90,
    w: 26,
    h: 26,
    abilities: ["claw", "catdash", "lives"],
    evoNames: ["Gatito", "Neko Shadow", "Nueve Vidas"],
  },
];
